version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8020:8020"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/cars-db
      - PUERTO=8020

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
